### ISSUE TITLE
Package health at 32%

### ISSUE THREAD

**Issue by ALMaclaine** [lamarrr/Spell#2]
Will you please maintain your package so that it's health is close to 100%. If you're going to keep a name as significant as spell then at least maintain it so pub.dev doesn't turn into npm.

https://pub.dev/packages/spell

The current package health is 32%.

**Comment by lamarrr** [comment]
Noted,
thanks! :)

**Comment by ALMaclaine** [comment]
Thank you

**Comment by lamarrr** [comment]
No, thank you! :)
